package wifi

import (
	"fmt"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// systemConnectionsDir is where NetworkManager stores keyfile connection
// profiles. NM loads every profile here at startup and auto-connects those
// with autoconnect=true.
const systemConnectionsDir = "/etc/NetworkManager/system-connections"

// homeConnectionFile is the fixed filename for the profile we generate. The
// filename is independent of the SSID (NM matches on the [connection] id, not
// the filename), so an SSID with characters awkward in a path is no problem.
const homeConnectionFile = "teslausb-home.nmconnection"

// RenderHomeKeyfile returns the NetworkManager keyfile contents for the home
// WiFi connection. The [connection] id is set to the SSID so that
// `nmcli connection up <ssid>` (used by ConnectToHome) resolves it.
//
// Keyfile values run verbatim to end-of-line, so passphrases containing '#',
// '!', etc. need no escaping; only a leading '#'/';' or an embedded newline
// would be a problem, and WPA passphrases contain neither.
func RenderHomeKeyfile(ssid, password string, hidden bool) string {
	var b strings.Builder
	b.WriteString("# Generated by teslausb from teslausb.toml [wifi]. Do not edit by hand.\n")
	b.WriteString("[connection]\n")
	fmt.Fprintf(&b, "id=%s\n", ssid)
	b.WriteString("type=wifi\n")
	b.WriteString("autoconnect=true\n")
	b.WriteString("\n[wifi]\n")
	fmt.Fprintf(&b, "ssid=%s\n", ssid)
	b.WriteString("mode=infrastructure\n")
	if hidden {
		b.WriteString("hidden=true\n")
	}
	b.WriteString("\n[wifi-security]\n")
	b.WriteString("key-mgmt=wpa-psk\n")
	fmt.Fprintf(&b, "psk=%s\n", password)
	b.WriteString("\n[ipv4]\nmethod=auto\n")
	b.WriteString("\n[ipv6]\nmethod=auto\n")
	return b.String()
}

// EnsureHomeConnection writes the home WiFi profile to NetworkManager's
// keyfile directory (mode 0600, as NM ignores world-readable profiles) and
// reloads NM so it picks up changes. It is idempotent: if the on-disk profile
// already matches, it does nothing and skips the reload.
//
// This is what makes the Buildroot image self-contained — that path has no
// Raspberry Pi Imager step to pre-seed a connection, so without this the
// daemon's `nmcli connection up` had no profile to activate.
func (m *Manager) EnsureHomeConnection(ssid, password string, hidden bool) error {
	if ssid == "" || password == "" {
		// Nothing to provision; caller relies on an externally-managed profile.
		return nil
	}

	desired := RenderHomeKeyfile(ssid, password, hidden)
	path := filepath.Join(systemConnectionsDir, homeConnectionFile)

	if existing, err := os.ReadFile(path); err == nil && string(existing) == desired {
		slog.Info("home wifi profile already up to date", "ssid", ssid)
		return nil
	}

	if err := os.MkdirAll(systemConnectionsDir, 0o700); err != nil {
		return fmt.Errorf("wifi: create %s: %w", systemConnectionsDir, err)
	}
	if err := os.WriteFile(path, []byte(desired), 0o600); err != nil {
		return fmt.Errorf("wifi: write %s: %w", path, err)
	}
	// Defensive: enforce 0600 even if the file pre-existed with looser perms.
	if err := os.Chmod(path, 0o600); err != nil {
		return fmt.Errorf("wifi: chmod %s: %w", path, err)
	}

	slog.Info("provisioned home wifi profile", "ssid", ssid, "path", path)

	if out, err := exec.Command("nmcli", "connection", "reload").CombinedOutput(); err != nil {
		return fmt.Errorf("wifi: nmcli connection reload: %s", strings.TrimSpace(string(out)))
	}
	return nil
}
